import java.io.*;
class ExampleException {
  void testMethod(int num) throws IOException, ArithmeticException {
    if (num == 1) {
      throw new IOException("IO Exception occured");
    } else
      throw new ArithmeticException("Arithmetic Exception occured");
  }
}
class TestExampleException {
  public static void main(String args[]) {
    try {
      ExampleException obj = new ExampleException();
      obj.testMethod(1);
    } catch (IOException ex) {
      System.out.println(ex);
    } catch (ArithmeticException ae) {
      System.out.println(ae);
    } finally {
      System.out.println("Finally block");
    }
    System.out.println("Rest of code continues");
  }
}